# Generated by Django 2.2.7 on 2020-05-06 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SNP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=70)),
                ('isolated_time', models.DateTimeField()),
                ('created_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('snp_type', models.IntegerField()),
                ('snp_site_1', models.CharField(max_length=1)),
                ('snp_site_2', models.CharField(max_length=1)),
                ('snp_site_3', models.CharField(max_length=1)),
                ('snp_site_4', models.CharField(max_length=1)),
                ('snp_site_5', models.CharField(max_length=1)),
                ('snp_site_6', models.CharField(max_length=1)),
                ('snp_site_7', models.CharField(max_length=1)),
                ('snp_site_8', models.CharField(max_length=1)),
                ('snp_site_9', models.CharField(max_length=1)),
                ('snp_site_10', models.CharField(max_length=1)),
                ('snp_site_11', models.CharField(max_length=1)),
                ('snp_site_12', models.CharField(max_length=1)),
                ('snp_site_13', models.CharField(max_length=1)),
                ('snp_site_14', models.CharField(max_length=1)),
                ('snp_site_15', models.CharField(max_length=1)),
                ('snp_site_16', models.CharField(max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
