# Generated by Django 3.0.3 on 2020-06-23 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snp',
            options={'verbose_name': 'snp明细', 'verbose_name_plural': 'snp明细'},
        ),
        migrations.AlterField(
            model_name='snp',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加者'),
        ),
        migrations.AlterField(
            model_name='snp',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='snp',
            name='isolated_time',
            field=models.DateTimeField(verbose_name='分离时间'),
        ),
        migrations.AlterField(
            model_name='snp',
            name='location',
            field=models.CharField(max_length=70, verbose_name='分离地点'),
        ),
        migrations.AlterField(
            model_name='snp',
            name='modified_time',
            field=models.DateTimeField(verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='snp',
            name='snp_type',
            field=models.IntegerField(verbose_name='snp类型'),
        ),
    ]
